name: 构建并部署到阿里云OSS

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches:
      - main
  # 手动触发部署
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: 构建VuePress并部署到OSS
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          # “最近更新时间”等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      # 设置 Node.js
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          # 使用稳定的 Node.js 版本
          node-version: 16
          # 缓存 npm 依赖
          cache: npm

      # 安装依赖
      - name: 安装依赖
        run: npm ci

      # 构建 VuePress 站点
      - name: 构建 VuePress 站点
        run: npm run build
        working-directory: ./notes # 确保在正确的目录下运行

      # 打印构建目录内容
      - name: 打印构建目录内容
        run: ls -al ./notes/.vuepress/dist

      # 配置阿里云 OSS 工具
      - name: 设置阿里云OSS工具
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-hongkong.aliyuncs.com
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}

      # 上传到阿里云 OSS
      - name: 部署到阿里云OSS
        run: ossutil cp -rf ./notes/.vuepress/dist/ oss://blog-area/
