name: 构建并部署到阿里云OSS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: 构建VuePress并部署到OSS
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v3

      # 设置Node.js环境
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # 使用稳定的 Node.js 版本
          cache: "npm"

      # 安装依赖
      - name: 安装依赖
        run: |
          npm ci
          npm install vuepress-theme-hope --save-dev

      # 构建VuePress
      - name: 构建VuePress
        run: npm run build
        working-directory: ./notes # 确保在正确的目录下运行

      # 打印构建目录内容
      - name: 打印构建目录内容
        run: ls -al ./notes/.vuepress/dist

      # 配置OSS工具
      - name: 设置阿里云OSS工具
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-hongkong.aliyuncs.com
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}

      # 上传到OSS
      - name: 部署到阿里云OSS
        run: ossutil cp -rf ./notes/.vuepress/dist/ oss://blog-area/
